resolver: lts-13.19
packages:
- .
extra-deps:
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
- git: https://github.com/drownbes/replica.git
  commit: 5ad6f2e965666a3fc5a37c4a84531e3b10361939
- git: https://github.com/pkamenarsky/concur.git
  commit: dc5347b35c79654d58fa95716f425ee7248504fb
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
